### ISSUE TITLE
Validate fails when HEAD is detached from a branch

### ISSUE THREAD

**Issue by upstart-swiss** [demisto/demisto-sdk#1484]
https://github.com/demisto/demisto-sdk/blob/b2c5a1871bb5405dc6eefafc1620a82ae1636ae2/demisto_sdk/commands/common/git_util.py#L423

This is failing in a pipeline that's operating on a specific commit. Recommend handling the exception and returning something else (maybe None?)
```
[2021-07-19T16:09:28.968Z] Traceback (most recent call last):
[2021-07-19T16:09:28.968Z]   File "/usr/local/bin/demisto-sdk", line 10, in <module>
[2021-07-19T16:09:28.968Z]     sys.exit(main())
[2021-07-19T16:09:28.968Z]   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
[2021-07-19T16:09:28.968Z]     return self.main(*args, **kwargs)
[2021-07-19T16:09:28.968Z]   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
[2021-07-19T16:09:28.968Z]     rv = self.invoke(ctx)
[2021-07-19T16:09:28.968Z]   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
[2021-07-19T16:09:28.968Z]     return _process_result(sub_ctx.command.invoke(sub_ctx))
[2021-07-19T16:09:28.968Z]   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
[2021-07-19T16:09:28.968Z]     return ctx.invoke(self.callback, **ctx.params)
[2021-07-19T16:09:28.968Z]   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
[2021-07-19T16:09:28.968Z]     return callback(*args, **kwargs)
[2021-07-19T16:09:28.968Z]   File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 73, in new_func
[2021-07-19T16:09:28.968Z]     return ctx.invoke(f, obj, *args, **kwargs)
[2021-07-19T16:09:28.968Z]   File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
[2021-07-19T16:09:28.968Z]     return callback(*args, **kwargs)
[2021-07-19T16:09:28.968Z]   File "/usr/local/lib/python3.7/dist-packages/demisto_sdk/__main__.py", line 420, in validate
[2021-07-19T16:09:28.968Z]     check_is_unskipped=not kwargs.get('allow_skipped', False),
[2021-07-19T16:09:28.968Z]   File "/usr/local/lib/python3.7/dist-packages/demisto_sdk/commands/validate/validate_manager.py", line 132, in __init__
[2021-07-19T16:09:28.968Z]     self.branch_name = self.git_util.get_current_working_branch()
[2021-07-19T16:09:28.969Z]   File "/usr/local/lib/python3.7/dist-packages/demisto_sdk/commands/common/git_util.py", line 423, in get_current_working_branch
[2021-07-19T16:09:28.969Z]     return str(self.repo.active_branch)
[2021-07-19T16:09:28.969Z]   File "/usr/local/lib/python3.7/dist-packages/git/repo/base.py", line 786, in active_branch
[2021-07-19T16:09:28.969Z]     return self.head.reference
[2021-07-19T16:09:28.969Z]   File "/usr/local/lib/python3.7/dist-packages/git/refs/symbolic.py", line 272, in _get_reference
[2021-07-19T16:09:28.969Z]     raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
```

**Comment by roysagi** [comment]
@upstart-swiss - Can you please specify what did you run? did you run the command in content repo? not sure returning None is necessarily the right call here as we expect a branch name not sure what the behavior would be.

**Comment by craigsands** [comment]
I've gotten this as well, ultimately telling me `TypeError: HEAD is a detached symbolic reference as it points to '<commit hash>'`. I receive this when running `demisto-sdk validate` as part of a pipeline. But when I run `demisto-sdk validate` locally, I receive success (everything is valid).

**Comment by upstart-swiss** [comment]
Found a hacky solution - we do a `git checkout -b <random value>` in the pipeline before running the command. Because this adds the branch tag, it makes the command happy.

I still don't understand why the command relies on the commit having a branch name and would love to see a fix (because this is hacky) but it lowers the issue priority for us.

**Comment by upstart-swiss** [comment]
Error
```
================= Running validation on branch d1551134b305526f95e10acfa4becf2552a9abd1 =================
Validating against main
Running on committed and staged files
Traceback (most recent call last):
  File "/Users/chrisschafer/gits/demisto_prod/venv/bin/demisto-sdk", line 8, in <module>
    sys.exit(main())
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/demisto_sdk/__main__.py", line 494, in validate
    return validator.run_validation()
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/demisto_sdk/commands/validate/validate_manager.py", line 211, in run_validation
    is_valid = self.run_validation_using_git()
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/demisto_sdk/commands/validate/validate_manager.py", line 677, in run_validation_using_git
    self.get_changed_files_from_git()
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/demisto_sdk/commands/validate/validate_manager.py", line 1297, in get_changed_files_from_git
    modified_files, added_files, renamed_files = self.get_unfiltered_changed_files_from_git()
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/demisto_sdk/commands/validate/validate_manager.py", line 1274, in get_unfiltered_changed_files_from_git
    modified_files = self.git_util.modified_files(prev_ver=self.prev_ver,
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/demisto_sdk/commands/common/git_util.py", line 39, in modified_files
    last_commit = self._only_last_commit(prev_ver, requested_status='M')
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/demisto_sdk/commands/common/git_util.py", line 403, in _only_last_commit
    if self.get_current_working_branch() != prev_ver:
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/demisto_sdk/commands/common/git_util.py", line 449, in get_current_working_branch
    return str(self.repo.active_branch)
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/git/repo/base.py", line 718, in active_branch
    return self.head.reference
  File "/Users/chrisschafer/gits/demisto_prod/venv/lib/python3.8/site-packages/git/refs/symbolic.py", line 272, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to 'd1551134b305526f95e10acfa4becf2552a9abd1'
(venv) chrisschafer@ChrisSchafer-MacBook-Pro demisto_prod % 
```
