### ISSUE TITLE
YMLSplitter does not work for relative paths

### ISSUE THREAD

**Issue by panw-pduncan** [demisto/demisto-sdk#1893]
```bash
$ python3 -m demisto_sdk split -i ./integration.yml
You are using demisto-sdk 1.6.0.
Starting migration of: integration.yml to dir: .
Traceback (most recent call last):
  File "/Users/pduncan/.pyenv/versions/3.8.12/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/pduncan/.pyenv/versions/3.8.12/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/pduncan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/demisto_sdk/__main__.py", line 2032, in <module>
    main()
  File "/Users/pduncan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pduncan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/pduncan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pduncan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pduncan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/pduncan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/pduncan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/pduncan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/demisto_sdk/__main__.py", line 207, in split
    return yml_splitter.extract_to_package_format()
  File "/Users/pduncan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/demisto_sdk/commands/split/ymlsplitter.py", line 102, in extract_to_package_format
    self.extract_code(code_file)
  File "/Users/pduncan/.pyenv/versions/3.8.12/lib/python3.8/site-packages/demisto_sdk/commands/split/ymlsplitter.py", line 241, in extract_code
    code_file_path = code_file_path.with_suffix(ext)
  File "/Users/pduncan/.pyenv/versions/3.8.12/lib/python3.8/pathlib.py", line 872, in with_suffix
    raise ValueError("%r has an empty name" % (self,))
ValueError: PosixPath('.') has an empty name
```

The above error occurs when trying to call split with a relative path, using a full path the code works.

```bash
WORKS:
python3 -m demisto_sdk split -i $(pwd)/integration.yml

DOES NOT WORK:
python3 -m demisto_sdk split -i ./integration.yml
```

This is backed by the included unit tests in `ymlsplitter_test.py` which only contain absolute paths to files.

**Expected Behavior**: Command supports relative pathing.

I do not know if any other commands act similarly.

**Comment by dorschw** [comment]
Hi, thanks for reporting the issue, we're looking at it and will update.

**Comment by dorschw** [comment]
@panw-pduncan 
The fix will be available on the upcoming release, version `1.6.1`. 
Please let us know if you have any further questions.
