### ISSUE TITLE
ERR_REQUIRE_ESM in mdx-parse-server.js

### ISSUE THREAD

**Issue by K-Yo** [demisto/demisto-sdk#2097]
When running `demisto-sdk validate -i Packs/X` I get the following error

```
internal/modules/cjs/loader.js:1015
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/user/code/git/xsoar/content-ci-cd-template/node_modules/@mdx-js/mdx/index.js
require() of ES modules is not supported.
require() of /home/user/code/git/xsoar/content-ci-cd-template/node_modules/@mdx-js/mdx/index.js from /home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/demisto_sdk/commands/common/mdx-parse-server.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/user/code/git/xsoar/content-ci-cd-template/node_modules/@mdx-js/mdx/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/demisto_sdk/commands/common/mdx-parse-server.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'ERR_REQUIRE_ESM'
}
Traceback (most recent call last):
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/bin/demisto-sdk", line 8, in <module>
    sys.exit(main())
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/demisto_sdk/__main__.py", line 520, in validate
    return validator.run_validation()
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/demisto_sdk/commands/validate/validate_manager.py", line 262, in run_validation
    is_valid = self.run_validation_on_specific_files()
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/demisto_sdk/commands/validate/validate_manager.py", line 326, in run_validation_on_specific_files
    files_validation_result.add(self.run_validations_on_pack(path)[0])
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/demisto_sdk/commands/validate/validate_manager.py", line 411, in run_validations_on_pack
    pack_entities_validation_results.add(self.run_validation_on_content_entities(content_entity_path,
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/demisto_sdk/commands/validate/validate_manager.py", line 445, in run_validation_on_content_entities
    content_entities_validation_results.add(self.run_validation_on_package(file_path,
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/demisto_sdk/commands/validate/validate_manager.py", line 456, in run_validation_on_package
    package_entities_validation_results.add(self.run_validations_on_file(file_path, pack_error_ignore_list))
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/demisto_sdk/commands/validate/validate_manager.py", line 618, in run_validations_on_file
    with ReadMeValidator.start_mdx_server(handle_error=self.handle_error):
  File "/home/user/.pyenv/versions/3.8.13/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/user/code/git/xsoar/content-ci-cd-template/.venv/lib/python3.8/site-packages/demisto_sdk/commands/common/hook_validations/readme.py", line 564, in start_mdx_server
    raise Exception(error_message)
Exception: Failed starting mdx server. stdout: .
Try running the following command: `npm install`
```

**Comment by K-Yo** [comment]
When changing

```js
const mdx = require('@mdx-js/mdx');
```

to

```js
const mdx = import('@mdx-js/mdx');
```

in https://github.com/demisto/demisto-sdk/blob/8c7eae108eecf3986bad9bda4075154c21165ca3/demisto_sdk/commands/common/mdx-parse-server.js#L1

I do not have the error anymore (but I’m not a js dev)

**Comment by K-Yo** [comment]
Hello @dorschw I see you reply to all issues (quite fast, congratulations!) but not this one, is there an issue with it?

thanks!

**Comment by dorschw** [comment]
this will be handled in https://jira-hq.paloaltonetworks.local/browse/CIAC-3022, and we'll close this issue once it's solved.

**Comment by dorschw** [comment]
Hey, we changed the way MDX is triggered
Please check it with v1.7.8, and let us know if it still reproduces
