### ISSUE TITLE
demisto-sdk lint not in virtual environment

### ISSUE THREAD

**Issue by soumenchakraborty-endace** [demisto/demisto-sdk#2122]
have installed a freshly minted centos 7 machine. Following this [page](https://xsoar.pan.dev/docs/tutorials/tut-setup-dev) all packages , pyenv , docker, python 3.8.13, etc. Bootstrap scripts runs fine. The virtual environment exists, still it complaints that sdk is not in the virtual machine. 

(venv) [root@xsoardev content]# demisto-sdk lint -i Packs/HelloWorld/Integrations/HelloWorld -vvv
You are using demisto-sdk 1.6.6.
demisto-sdk lint not in virtual environment, Python2 lints will fail, use "source .hooks/bootstrap" to create the virtual environment
2022-05-24T21:04:31Z [DEBUG]: Content path /root/demisto/content
2022-05-24T21:04:31Z [DEBUG]: Test requirements successfully collected for python 2:
 ['astroid==1.6.6', 'atomicwrites==1.4.0', 'attrs==21.2.0', 'backports.functools-lru-cache==1.6.4', 'certifi==2021.5.30', 'chardet==4.0.0', 'configparser==4.0.2', 'contextlib2==0.6.0.post1', 'coverage==5.5', 'enum34==1.1.10', 'execnet==1.9.0', 'funcsigs==1.0.2', 'futures==3.3.0', 'idna==2.10', 'importlib-metadata==2.1.1', 'isort==4.3.21', 'lazy-object-proxy==1.6.0', 'mccabe==0.6.1', 'mock==3.0.5', 'more-itertools==5.0.0', 'packaging==20.9', 'pathlib2==2.3.5', 'pluggy==0.13.1', 'py==1.10.0', 'pylint==1.9.5', 'pyparsing==2.4.7', 'pytest==4.6.11', 'pytest-cov==2.12.1', 'pytest-forked==1.3.0', 'pytest-json==0.4.0', 'pytest-mock==2.0.0', 'pytest-xdist==1.34.0', 'requests==2.25.1', 'requests-mock==1.9.3', 'scandir==1.10.0', 'singledispatch==3.6.2', 'six==1.16.0', 'toml==0.10.2', 'urllib3==1.26.6', 'wcwidth==0.2.5', 'wrapt==1.12.1', 'zipp==1.2.0']
2022-05-24T21:04:31Z [DEBUG]: Test requirements successfully collected for python 3:
 ['astroid==2.9.3', 'attrs==21.4.0', 'certifi==2021.10.8', 'charset-normalizer==2.0.12', 'coverage==6.3.1', 'execnet==1.9.0', 'freezegun==1.1.0', 'hypothesis==6.36.2', 'idna==3.3', 'iniconfig==1.1.1', 'isort==5.10.1', 'lazy-object-proxy==1.7.1', 'mccabe==0.6.1', 'multidict==6.0.2', 'packaging==21.3', 'platformdirs==2.5.0', 'pluggy==1.0.0', 'py==1.11.0', 'pylint==2.12.2', 'pyparsing==3.0.7', 'pytest==7.0.1', 'pytest-asyncio==0.18.1', 'pytest-cov==3.0.0', 'pytest-datadir-ng==1.1.1', 'pytest-forked==1.4.0', 'pytest-json==0.4.0', 'pytest-mock==3.7.0', 'pytest-xdist==2.5.0', 'python-dateutil==2.8.2', 'pyyaml==6.0', 'requests==2.27.1', 'requests-mock==1.9.3', 'setuptools==60.9.1', 'six==1.16.0', 'sortedcontainers==2.4.0', 'toml==0.10.2', 'tomli==2.0.1', 'urllib3==1.26.8', 'vcrpy==4.1.1', 'wrapt==1.13.3', 'yarl==1.7.2']
2022-05-24T21:04:31Z [DEBUG]: read file /root/demisto/content/Tests/demistomock/demistomock.py
2022-05-24T21:04:31Z [DEBUG]: read file /root/demisto/content/Tests/scripts/dev_envs/pytest/conftest.py
2022-05-24T21:04:31Z [DEBUG]: read file /root/demisto/content/Packs/Base/Scripts/CommonServerPython/CommonServerPython.py
2022-05-24T21:04:31Z [DEBUG]: read file /root/demisto/content/Tests/demistomock/demistomock.ps1
2022-05-24T21:04:31Z [DEBUG]: read file /root/demisto/content/Packs/Base/Scripts/CommonServerPowerShell/CommonServerPowerShell.ps1
2022-05-24T21:04:31Z [DEBUG]: Test mandatory modules successfully collected
Traceback (most recent call last):
  File "/root/demisto/content/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/demisto/content/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/root/demisto/content/venv/lib/python3.8/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/demisto/content/venv/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/root/demisto/content/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/root/demisto/content/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/demisto/content/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/demisto/content/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/demisto/content/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/root/demisto/content/venv/lib/python3.8/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/demisto/content/venv/lib/python3.8/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/root/demisto/content/venv/lib/python3.8/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/root/demisto/content/venv/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/root/demisto/content/venv/lib/python3.8/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/root/demisto/content/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/root/demisto/content/venv/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/demisto/content/venv/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/root/demisto/content/venv/lib/python3.8/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/demisto/content/venv/bin/demisto-sdk", line 8, in <module>
    sys.exit(main())
  File "/root/demisto/content/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/demisto/content/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/demisto/content/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/demisto/content/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/demisto/content/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/demisto/content/venv/lib/python3.8/site-packages/demisto_sdk/__main__.py", line 696, in lint
    lint_manager = LintManager(
  File "/root/demisto/content/venv/lib/python3.8/site-packages/demisto_sdk/commands/lint/lint_manager.py", line 74, in __init__
    self._facts: dict = self._gather_facts()
  File "/root/demisto/content/venv/lib/python3.8/site-packages/demisto_sdk/commands/lint/lint_manager.py", line 179, in _gather_facts
    docker_client: docker.DockerClient = docker.from_env()
  File "/root/demisto/content/venv/lib/python3.8/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/root/demisto/content/venv/lib/python3.8/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/root/demisto/content/venv/lib/python3.8/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/root/demisto/content/venv/lib/python3.8/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
(venv) [root@xsoardev content]#
(venv) [root@xsoardev content]# source .hooks/bootstrap
Skipping install of pre-commit hook as it already exists.
If you want to re-install: 'rm /root/demisto/content/.git/hooks/pre-commit' and then run this script again.
=======================
Skipping virtual env setup as directory /root/demisto/content/venv exists.
If you want to re-install: 'rm -r /root/demisto/content/venv' and then run this script again.
=======================
Skipping npm node modules as 'npm' command was not found!!
node and npm are optional but recommended. We use node for validating README files.
You can install node and npm on your machine.
and then run: 'npm install'
(venv) [root@xsoardev content]#

(venv) [root@xsoardev content]# source .hooks/bootstrap
Skipping install of pre-commit hook as it already exists.
If you want to re-install: 'rm /root/demisto/content/.git/hooks/pre-commit' and then run this script again.
=======================
Skipping virtual env setup as directory /root/demisto/content/venv exists.
If you want to re-install: 'rm -r /root/demisto/content/venv' and then run this script again.
=======================
Skipping npm node modules as 'npm' command was not found!!
node and npm are optional but recommended. We use node for validating README files.
You can install node and npm on your machine.
and then run: 'npm install'
(venv) [root@xsoardev content]#

[root@xsoardev content]# pyenv versions
  system
* 3.8.13 (set by /root/demisto/content/.python-version)
[root@xsoardev-partner-1 content]# python -V
Python 3.8.13
[root@xsoardev-partner-1 content]# . ./venv/bin/activate
(venv) [root@xsoardev-partner-1 content]#

**Comment by dorschw** [comment]
Hi, thanks for opening an issue
We are aware of this message printed, and it's handled internally (CIAC-2941).

Validating python3 content should be functional. You may need to install npm and then run `npm install` (a different issue that rises from the logs you attached). 

We'll close this issue as when a fix is implemented.

**Comment by dorschw** [comment]
This was solved in a recent version. Please upgrade the demisto-sdk (`pip install --update demisto-sdk`). If this persists, please re-open the issue.
