### ISSUE TITLE
Download cannot happen without a git repository and an "origin" remote

### ISSUE THREAD

**Issue by K-Yo** [demisto/demisto-sdk#2229]
It would be nice to use `demisto-sdk download` for several use-cases, such as downloading content to a folder that is not a git repository.

---

When I use `demisto-sdk download` to a folder that is not a git repository, I get the following stack trace:

```
You are using demisto-sdk 1.6.9.
Please run demisto-sdk in content repository - Aborting!
Traceback (most recent call last):
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/common/git_util.py", line 17, in __init__
    self.repo = Repo(Path.cwd(), search_parent_directories=True)
  File "~/project/.venv/lib/python3.9/site-packages/git/repo/base.py", line 224, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "~/project/.venv/lib/python3.9/site-packages/git/repo/base.py", line 307, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/project/.venv/bin/demisto-sdk", line 8, in <module>
    sys.exit(main())
  File "~/project/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "~/project/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "~/project/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/project/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/project/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/__main__.py", line 1013, in download
    from demisto_sdk.commands.download.downloader import Downloader
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/download/downloader.py", line 36, in <module>
    from demisto_sdk.commands.format.format_module import format_manager
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/format/format_module.py", line 15, in <module>
    from demisto_sdk.commands.format.update_classifier import (
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/format/update_classifier.py", line 11, in <module>
    from demisto_sdk.commands.format.update_generic_json import BaseUpdateJSON
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/format/update_generic_json.py", line 13, in <module>
    from demisto_sdk.commands.format.update_generic import BaseUpdate
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/format/update_generic.py", line 21, in <module>
    from demisto_sdk.commands.validate.validate_manager import ValidateManager
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/validate/validate_manager.py", line 68, in <module>
    from demisto_sdk.commands.common.hook_validations.pack_unique_files import \
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/common/hook_validations/pack_unique_files.py", line 72, in <module>
    class PackUniqueFilesValidator(BaseValidator):
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/common/hook_validations/pack_unique_files.py", line 76, in PackUniqueFilesValidator
    git_util = GitUtil(repo=Content.git())
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/common/git_util.py", line 19, in __init__
    raise InvalidGitRepositoryError("Unable to find Repository from current working directory - aborting")
git.exc.InvalidGitRepositoryError: Unable to find Repository from current working directory - aborting
```

When it is a git repository but doesn’t have a remote named `origin` it fails also with:

```
You are using demisto-sdk 1.6.9.
Traceback (most recent call last):
  File "~/project/.venv/bin/demisto-sdk", line 8, in <module>
    sys.exit(main())
  File "~/project/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "~/project/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "~/project/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/project/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/project/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/__main__.py", line 1013, in download
    from demisto_sdk.commands.download.downloader import Downloader
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/download/downloader.py", line 36, in <module>
    from demisto_sdk.commands.format.format_module import format_manager
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/format/format_module.py", line 15, in <module>
    from demisto_sdk.commands.format.update_classifier import (
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/format/update_classifier.py", line 11, in <module>
    from demisto_sdk.commands.format.update_generic_json import BaseUpdateJSON
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/format/update_generic_json.py", line 13, in <module>
    from demisto_sdk.commands.format.update_generic import BaseUpdate
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/format/update_generic.py", line 21, in <module>
    from demisto_sdk.commands.validate.validate_manager import ValidateManager
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/validate/validate_manager.py", line 22, in <module>
    from demisto_sdk.commands.common.content import Content
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/common/content/__init__.py", line 6, in <module>
    from .content import *  # lgtm [py/polluting-import]
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/common/content/content.py", line 12, in <module>
    from demisto_sdk.commands.common.content.objects.pack_objects.pack import Pack
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/common/content/objects/pack_objects/__init__.py", line 32, in <module>
    from .pack_metadata.pack_metadata import PackMetaData
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/common/content/objects/pack_objects/pack_metadata/pack_metadata.py", line 17, in <module>
    from demisto_sdk.commands.find_dependencies.find_dependencies import \
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/find_dependencies/find_dependencies.py", line 34, in <module>
    PACKS_FULL_PATH = os.path.join(get_content_path(), PACKS_DIR)  # full path to Packs folder in content repo
  File "~/project/.venv/lib/python3.9/site-packages/demisto_sdk/commands/common/tools.py", line 1580, in get_content_path
    remote_url = git_repo.remote().urls.__next__()
  File "~/project/.venv/lib/python3.9/site-packages/git/repo/base.py", line 358, in remote
    raise ValueError("Remote named '%s' didn't exist" % name)
ValueError: Remote named 'origin' didn't exist
```

**Comment by dorschw** [comment]
thanks @K-Yo, this issue is tracked internally as [CIAC-3517](https://jira-hq.paloaltonetworks.local/browse/CIAC-3517)

**Comment by MosheEichler** [comment]
Hey @K-Yo 
I'm seeing you are using a very old version of demisto-sdk (1.6.9)
Should already be fixed since version 1.14.4 can you please confirm (please update your demisto-sdk and run again)

**Comment by MosheEichler** [comment]
Hey @K-Yo Any updates?

**Comment by dorschw** [comment]
Please reopen this issue if it reproduces.
