### ISSUE TITLE
demisto-sdk does errors out when "File Type" is "betaintegration"

### ISSUE THREAD

**Issue by PaulBartruff** [demisto/demisto-sdk#2263]
``` sh
(virtual310) [sysop@xsoardev content]$ git branch sdktest
(virtual310) [sysop@xsoardev content]$ git checkout sdktest
Switched to branch 'sdktest'
(virtual310) [sysop@xsoardev content]$ mkdir -p Packs/sdktest
(virtual310) [sysop@xsoardev content]$ demisto-sdk download -lf
You are using demisto-sdk 1.7.1.

The following files are available to be downloaded from Demisto instance:

FILE NAME                                                                  FILE TYPE
-------------------------------------------------------------------------  ----------------
...
Proofpoint Threat Response_Custom                                          betaintegration
...
(virtual310) [sysop@xsoardev content]$ demisto-sdk download -i "Proofpoint Threat Response_Custom" -o Packs/sdktest/
You are using demisto-sdk 1.7.1.

Demisto instance: Enumerating objects: 1, done.
Demisto instance: Receiving objects: 100% (1/1), done.

Traceback (most recent call last):
  File "/home/sysop/repos/virtual310/bin/demisto-sdk", line 8, in <module>
    sys.exit(main())
  File "/home/sysop/repos/virtual310/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/sysop/repos/virtual310/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sysop/repos/virtual310/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sysop/repos/virtual310/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sysop/repos/virtual310/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sysop/repos/virtual310/lib/python3.10/site-packages/demisto_sdk/__main__.py", line 1017, in download
    return downloader.download()
  File "/home/sysop/repos/virtual310/lib/python3.10/site-packages/demisto_sdk/commands/download/downloader.py", line 130, in download
    exit_code: int = self.download_manager()
  File "/home/sysop/repos/virtual310/lib/python3.10/site-packages/demisto_sdk/commands/download/downloader.py", line 155, in download_manager
    self.merge_into_pack()
  File "/home/sysop/repos/virtual310/lib/python3.10/site-packages/demisto_sdk/commands/download/downloader.py", line 686, in merge_into_pack
    self.merge_and_extract_new_file(custom_content_object)
  File "/home/sysop/repos/virtual310/lib/python3.10/site-packages/demisto_sdk/commands/download/downloader.py", line 800, in merge_and_extract_new_file
    extractor.extract_to_package_format()
  File "/home/sysop/repos/virtual310/lib/python3.10/site-packages/demisto_sdk/commands/split/ymlsplitter.py", line 107, in extract_to_package_format
    self.extract_code(code_file)
  File "/home/sysop/repos/virtual310/lib/python3.10/site-packages/demisto_sdk/commands/split/ymlsplitter.py", line 258, in extract_code
    lang_type = self.yml_data['type']
  File "/home/sysop/repos/virtual310/lib/python3.10/site-packages/ruamel/yaml/comments.py", line 927, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'type'
(virtual310) [sysop@xsoardev content]$ 
``` 
@PaulBartruff

**Comment by dorschw** [comment]
Internally tracked under [CIAC-3784](https://jira-hq.paloaltonetworks.local/browse/CIAC-3784)
