### ISSUE TITLE
"demisto-sdk run" command doesn't work in XSIAM because no playground

### ISSUE THREAD

**Issue by johnnywilkes** [demisto/demisto-sdk#2306]
Was running the following command:
`demisto-sdk run -q "getassetinternetexposure asm_id_list=e06f15ce-9ab1-3460-8a31-000ac6d2d37e"`

and got the following:
```
You are using demisto-sdk 1.7.3.
Traceback (most recent call last):
  File "/Users/jwilkes/Code/content-JW-Fork/.venv/bin/demisto-sdk", line 8, in <module>
    sys.exit(main())
  File "/Users/jwilkes/Code/content-JW-Fork/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jwilkes/Code/content-JW-Fork/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/jwilkes/Code/content-JW-Fork/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jwilkes/Code/content-JW-Fork/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jwilkes/Code/content-JW-Fork/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jwilkes/Code/content-JW-Fork/.venv/lib/python3.10/site-packages/demisto_sdk/__main__.py", line 1096, in run
    return runner.run()
  File "/Users/jwilkes/Code/content-JW-Fork/.venv/lib/python3.10/site-packages/demisto_sdk/commands/run_cmd/runner.py", line 57, in run
    playground_id = self._get_playground_id()
  File "/Users/jwilkes/Code/content-JW-Fork/.venv/lib/python3.10/site-packages/demisto_sdk/commands/run_cmd/runner.py", line 97, in _get_playground_id
    raise RuntimeError(
RuntimeError: No playgrounds were detected in the environment.
```

Is it possible this doesn't work in XSIAM because there is no playground?  Is there any other way to get it to work on XSIAM?

**Comment by dorschw** [comment]
Hi, we don't support running in XSIAM yet. 
We are tracking it internally as [CIAC-3972](https://jira-hq.paloaltonetworks.local/browse/CIAC-3972)

**Comment by johnnywilkes** [comment]
@dorschw , you don't support "demisto-sdk run" command in XSIAM or all "demisto-sdk"?

**Comment by dorschw** [comment]
The `run` command is not yet supported on XSIAM.
We are working on supporting XSIAM in the various demisto-sdk commands.
