### ISSUE TITLE
LegacyVersion has been removed from packaging

### ISSUE THREAD

**Issue by netjordan** [demisto/demisto-sdk#2556]
I have installed demisto-sdk today, however when running commands, the following error is given
```
+ demisto-sdk --version
Traceback (most recent call last):
  File "/data/jenkins/workspace/xsoar-content/venv/bin/demisto-sdk", line 5, in <module>
    from demisto_sdk.__main__ import main
  File "/data/jenkins/workspace/xsoar-content/venv/lib/python3.10/site-packages/demisto_sdk/__main__.py", line 19, in <module>
    from demisto_sdk.commands.common.content_constant_paths import ALL_PACKS_DEPENDENCIES_DEFAULT_PATH
  File "/data/jenkins/workspace/xsoar-content/venv/lib/python3.10/site-packages/demisto_sdk/commands/common/content_constant_paths.py", line 3, in <module>
    from demisto_sdk.commands.common.tools import get_content_path
  File "/data/jenkins/workspace/xsoar-content/venv/lib/python3.10/site-packages/demisto_sdk/commands/common/tools.py", line 30, in <module>
    from packaging.version import LegacyVersion, Version, parse
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/data/jenkins/workspace/xsoar-content/venv/lib/python3.10/site-packages/packaging/version.py)
```

Upon investigating, I can see the latest version of packaging removes LegacyVersion - https://github.com/pypa/packaging/releases/tag/22.0

**Comment by dorschw** [comment]
Hi, thanks. #2559 applies a patch that locks packaging to `<22`, and we have an [internal issue to replace it](https://jira-hq.paloaltonetworks.local/browse/CIAC-729).
