### ISSUE TITLE
generate-test-playbook

### ISSUE THREAD

**Issue by yilmazdincer** [demisto/demisto-sdk#3223]
`demisto-sdk generate-test-playbook -i Packs/MISP/Integrations/MISPV3/MISPV3.yml -n playbook-MISPInfo_Test.yml -o TestPlaybooks/NonCircleTests/ -e Packs/MISP/Integrations/MISPV3/command_examples -c misp-add-user,misp-get-organization-info,misp-get-role-info`

Error:
`Traceback (most recent call last):
  File "/home/x/content/.venv/bin/demisto-sdk", line 8, in <module>
    sys.exit(main())
  File "/home/x/content/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/x/content/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/x/content/.venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/x/content/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/x/content/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/x/content/.venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/x/content/.venv/lib/python3.10/site-packages/demisto_sdk/__main__.py", line 156, in wrapper
    return func(*args, **kwargs)
  File "/home/x/content/.venv/lib/python3.10/site-packages/demisto_sdk/__main__.py", line 1834, in generate_test_playbook
    generator = PlaybookTestsGenerator(file_type=file_type.value, **kwargs)
TypeError: PlaybookTestsGenerator.__init__() got an unexpected keyword argument 'console_log_threshold'`

**Comment by dorschw** [comment]
Thank you for opening an issue
This is tracked internally as [CIAC-7294](https://jira-hq.paloaltonetworks.local/browse/CIAC-7294)

**Comment by tkatzir** [comment]
@yilmazdincer,
What version of demisto-sdk are you using?
Could you please try with the latest version?
