### ISSUE TITLE
[BUG] demisto-sdk run cmd unknown failure and missing args

### ISSUE THREAD

**Issue by cmd-not-found** [demisto/demisto-sdk#811]
## Issue description
- Unknown failure for the `demisto-sdk run` command. 
- The `demisto-sdk run` command also missing `-k` option, even though the docs specify as an option. 

> **NOTE:** `--insecure` works as expected, so `-k` minor bug. 
> **REF:** https://github.com/demisto/demisto-sdk/tree/master/demisto_sdk/commands/run_cmd#arguments

## What's the expected result?

- Expected ability to run command using `demisto-sdk`.
- Expected ability to use `-k` for `insecure` mode (i.e. from docs: `demisto-sdk run -q '!gct-translate-text text="ciao" target="iw"' -k`). 

## What's the actual result?

- Unknown failure associated with playground.

```
(venv) jberry@Metaverse content % demisto-sdk run -q '!domain domain=foobar.com' --insecure
Traceback (most recent call last):
  File "/Users/jberry/projects/xsoar/content/venv/bin/demisto-sdk", line 8, in <module>
    sys.exit(main())
  File "/Users/jberry/projects/xsoar/content/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jberry/projects/xsoar/content/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jberry/projects/xsoar/content/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jberry/projects/xsoar/content/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jberry/projects/xsoar/content/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jberry/projects/xsoar/content/venv/lib/python3.8/site-packages/demisto_sdk/__main__.py", line 554, in run
    return runner.run()
  File "/Users/jberry/projects/xsoar/content/venv/lib/python3.8/site-packages/demisto_sdk/commands/run_cmd/runner.py", line 53, in run
    playground_id = self._get_playground_id()
  File "/Users/jberry/projects/xsoar/content/venv/lib/python3.8/site-packages/demisto_sdk/commands/run_cmd/runner.py", line 94, in _get_playground_id
    raise RuntimeError(
RuntimeError: Got unexpected amount of results in getPlaygroundInvestigationID. Response was: 0
```

- Attempted to use `-k` as a `run` command argument, but got error message not found.

```
(venv) jberry@Metaverse content % demisto-sdk run -q '!ip ip=1.2.3.4' -k
Usage: demisto-sdk run [OPTIONS]

Error: no such option: -k
```

## Additional details
- To validate that the API is configured for my CommunityEdition test instance correctly, I created and downloaded a `TestScript` to validate. To me, this means the `DEMISTO_BASE_URL` and `DEMISTO_API_KEY` are set correctly.

```
(venv) jberry@Metaverse content % demisto-sdk download --insecure -o Packs/HelloWorld -i "TestScript"

Demisto instance: Enumerating objects: 1, done.
Demisto instance: Receiving objects: 100% (1/1), done.

- Added Script "TestScript"

1 file added.
(venv) jberry@Metaverse content % 
```

- `demisto-sdk` Version
```
(venv) jberry@Metaverse content % demisto-sdk --version
demisto-sdk 1.2.4
```

- demisto server version (Community Edition License)

```
2020-10-11 03:47:26.2533 info Demisto version: 6.0.1, Git SHA1 commit: 1efb045ad54156c096ae0178a567577c36b0a318 (Sat Sep 19 08:37:09 UTC 2020), Server Build number: 84583, Web Client Git SHA1 commit: f3c9b47fbd6b2b00276fa9f1684c2c1af7f77f06 (2020-09-16T11:33:28.856Z) (source: /home/circleci/.go_workspace/src/github.com/demisto/server/server.go:560) 
```

**Comment by Itay4** [comment]
@cmd-not-found Thanks for reporting, we will handle this

**Comment by cmd-not-found** [comment]
@Itay4 - looking closer at this. I actually think this was a bizarre issue on my end. It seems my test XSOAR server doesn't actually have a Playground for some reason, which is what's causing this to fail... the `_get_playground_id()` isn't finding it because there's some odd behavior going on with the server itself, not `demisto-sdk` or `demisto-py`. In the UI, there's actually no `Playground` listed on the left-hand menu either. Since this is just a test server, it doesn't matter much.

I'm running the server locally on a VMWare VM using `Ubuntu 18.04.5`. I spun up a new fresh VM and reinstalled XSOAR and now the `demisto-sdk` commands that failed (as described above) all work with no issue. I think the "unknown error" part of this issue is resolved. Feel free to close (or leave open for the `-k` option). Thanks!
